version: "3.7"
services:
  nginx:
    image: "nginx:latest"
    container_name: iknow-main-frontend-container
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html
    ports:
      - "9002:80"

