name: Deploy

on:
  push:
    branches:
      - CICD

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: create nginx conf
        run: |
          mkdir ~/imf/conf
          echo "${{ secrets.NGINX_CONF}}" >> ~/imf/conf/nginx.conf

      - name: Create .env file
        run: |
          echo "${{ secrets._ENV_PRODUCTION}}" >> ~/imf/.env.production
      
      - name: Create docker files
        run: |
          echo "${{ secrets.DOCKER_COMPOSE_YML}}" >> ~/imf/docker-compose.yml
          echo "${{ secrets.DOCKERFILE}}" >> ~/imf/Dockerfile

      - name: Build
        run: npm run build

      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./dist/*"
          target: "~/imf"
      


  deploy:
    needs: build
    name: deploy-app
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            ls
            docker-compose -f ~/imf/docker-compose.yml up -d
            docker image prune -f
            docker logout

            docker-compose up -d

