name: Deploy

on:
  push:
    branches:
      - CICD

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./dist/*"
          target: "~/imf"

  deploy:
    needs: build
    name: deploy-app
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_4800H }}
          username: ${{ secrets.USERNAME_4800H }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/imf
            ls

